notifications:
    email: false
language: Ruby  
script:
    - cd build/unit_test
    - make
    - make coverage
#    - cd ../wrangle
#    - rake clean
#    - rake compile
#    - rake package
#    - cd gem
#    - bundle install
#    - rake
